server:
  port: 8800
spring:
  application:
    name: business-order-service-zjf
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.185.155:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://47.106.185.155:8848
  cloud:
    subscribed-services: "*"
